version: "3"

services:
  tomcat:
    build: .
    container_name: tomcat
    expose:
      - 8443
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - /usr/share/tomcat/logs:/usr/local/tomcat/logs
      - ./webapps.dist:/usr/local/tomcat/webapps
      # - ./conf:/usr/local/tomcat/conf
      # - /usr/share/tomcat/bin:/usr/local/tomcat/bin
      # - /usr/share/tomcat/lib:/usr/local/tomcat/lib
    # command:
    #   - auditctl -w ./conf -p wa -k tomcat

