version: "3"

services:
  tomcat:
    build: .
    container_name: tomcat-container
    expose:
      - 8080
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - /var/log/tomcat:/usr/local/tomcat/logs
      - ./webapps.dist:/usr/local/tomcat/webapps
